### PR TITLE
Generic cache interface

### PR DESCRIPTION
**Pull request by abdurahmanadilovic**
Hi kezhenxu94, 

As we discussed before this introduces types to the cache interface. I made the existing Cache interface extend the new GenericTypedCache<Any, Any> and the old tests work as is, on top of that, I added new tests for the new GenericTypedCache interface. However, I am not sure about couple of things:

1. Naming, should `GenericTypedCache` be just `GenericCache`? Seems simpler
2. I introduced a new package `typed` for typed implementations of the existing cache implementations. So far I only added `PerpetualCacheTyped` class. Should I add the rest of typed implementations? Do we need duplicate implementations just for the typed version? Maybe the `GenericTypedCache` interface is all that is needed?
3. I created a new base class for typed tests, not sure if its needed since the tests are the same? 
4. Does this complicate things? Do we even need a typed interface? Did you experience any hindrance while using the library without generics? In my project I am using types so I don't have to cast things but I am not sure if its that big of a deal...

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@abdurahmanadilovic thanks, I'll have a detail look soon

**Comment by kezhenxu94** [comment]
> 1. Naming, should `GenericTypedCache` be just `GenericCache`? Seems simpler

`GenericCache` is good to me, it's simpler, please rename :)

> 2. Do we need duplicate implementations just for the typed version? 

Don't do that, bad idea IMO

> Maybe the `GenericTypedCache` interface is all that is needed?

Let's just keep one generic version, and rewrite the existed implementations with this version

> 3. I created a new base class for typed tests, not sure if its needed since the tests are the same?

After rewriting based on the (2), we don't need this, right?

> 4. Does this complicate things? Do we even need a typed interface? Did you experience any hindrance while using the library without generics? In my project I am using types so I don't have to cast things but I am not sure if its that big of a deal...

I didn't introduce generic types just to simplify things, but non-typed version can be simply extended from the generic version, so I'd like to have this and, if needed, give some hints in the docs on how to have non-typed cache, such as `typealias Cache = GenericCache<Any, Any>`

This pull request introduces good enhancement that I'd like to have, thanks

**Comment by abdurahmanadilovic** [comment]
Hi @kezhenxu94,

I hope you are doing fine. I pushed latest changes to this branch and I have a question:
I can't make SoftCache and WeakCache implementations type safe since they don't store values directly, they wrap values inside SoftEntry / WeakEntry type. Should I add the typealias
```kotlin
typealias Cache = GenericCache<Any,Any>
```
and make SoftCache and WeakCache implement Cache instead of GenericCache?

Also, will this PR break backward compatibility with the old version of this library, since this PR changes base implementations to have types?

**Comment by kezhenxu94** [comment]
> Hi @kezhenxu94,
> 
> 
> 
> I hope you are doing fine. I pushed latest changes to this branch and I have a question:
> 
> I can't make SoftCache and WeakCache implementations type safe since they don't store values directly, they wrap values inside SoftEntry / WeakEntry type. Should I add the typealias
> 
> ```kotlin
> 
> typealias Cache = GenericCache<Any,Any>
> 
> ```
> 
> and make SoftCache and WeakCache implement Cache instead of GenericCache?
> 
> 
> 
> Also, will this PR break backward compatibility with the old version of this library, since this PR changes base implementations to have types?

Hi @abdurahmanadilovic thanks, but what’s the difficulty to make SoftCache generic? I have not my MacBook at hand, but I guess you can still make SoftCache generic (`SoftCache<K, V)`) and the `delegate` type of `Cache<K, V>`, does it make sense?

**Comment by kezhenxu94** [comment]
@abdurahmanadilovic good to me, please go ahead

**Review by kezhenxu94 — APPROVED** [review]
LGTM, thanks very much for bringing this 🎉

**Comment by abdurahmanadilovic** [comment]
@kezhenxu94 thanks for accepting this, pleasure working with you :)

**Comment by kezhenxu94** [comment]
> @kezhenxu94 thanks for accepting this, pleasure working with you :)

Me too, pleasure to work with you, hope there're more collaborations in the future 😄

**Pull request merged**
